2025-07-21 16:05:07,581 INFO    MainThread:827 [wandb_setup.py:_flush():70] Current SDK version is 0.19.11
2025-07-21 16:05:07,582 INFO    MainThread:827 [wandb_setup.py:_flush():70] Configure stats pid to 827
2025-07-21 16:05:07,582 INFO    MainThread:827 [wandb_setup.py:_flush():70] Loading settings from /root/.config/wandb/settings
2025-07-21 16:05:07,582 INFO    MainThread:827 [wandb_setup.py:_flush():70] Loading settings from /fs-computility/mabasic/fanyuchen/Rethink-Search/ZeroSearch/wandb/settings
2025-07-21 16:05:07,582 INFO    MainThread:827 [wandb_setup.py:_flush():70] Loading settings from environment variables
2025-07-21 16:05:07,582 INFO    MainThread:827 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /fs-computility/mabasic/fanyuchen/Rethink-Search/ZeroSearch/wandb/run-20250721_160507-0hcd3i13/logs/debug.log
2025-07-21 16:05:07,582 INFO    MainThread:827 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /fs-computility/mabasic/fanyuchen/Rethink-Search/ZeroSearch/wandb/run-20250721_160507-0hcd3i13/logs/debug-internal.log
2025-07-21 16:05:07,582 INFO    MainThread:827 [wandb_init.py:init():852] calling init triggers
2025-07-21 16:05:07,582 INFO    MainThread:827 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'data': {'tokenizer': None, 'train_files': ['/fs-computility/mabasic/fanyuchen/Rethink-Search_tmp/verl_temp/ZeroSearch_dataset/train.parquet'], 'val_files': ['/fs-computility/mabasic/fanyuchen/Rethink-Search_tmp/verl_temp/ZeroSearch_dataset/test.parquet'], 'train_data_num': None, 'val_data_num': None, 'prompt_key': 'prompt', 'max_prompt_length': 1024, 'max_response_length': 4096, 'max_start_length': 256, 'max_obs_length': 512, 'train_batch_size': 64, 'val_batch_size': 1312, 'return_raw_input_ids': False, 'return_raw_chat': False, 'shuffle_train_dataloader': True}, 'actor_rollout_ref': {'hybrid_engine': True, 'model': {'path': '/fs-computility/mabasic/shared/models/Llama-3.2-3B-Instruct', 'external_lib': None, 'override_config': {}, 'enable_gradient_checkpointing': True, 'use_remove_padding': True}, 'actor': {'strategy': 'fsdp', 'ppo_mini_batch_size': 256, 'ppo_micro_batch_size': 128, 'use_dynamic_bsz': False, 'ppo_max_token_len_per_gpu': 16384, 'grad_clip': 1.0, 'state_masking': False, 'clip_ratio': 0.2, 'entropy_coeff': 0, 'use_kl_loss': True, 'kl_loss_coef': 0.001, 'kl_loss_type': 'low_var_kl', 'ppo_epochs': 1, 'shuffle': False, 'ulysses_sequence_parallel_size': 1, 'optim': {'lr': 1e-06, 'lr_warmup_steps_ratio': 0.02, 'min_lr_ratio': None, 'warmup_style': 'constant', 'total_training_steps': 13250}, 'fsdp_config': {'wrap_policy': {'min_num_params': 0}, 'param_offload': True, 'grad_offload': False, 'optimizer_offload': True, 'fsdp_size': -1}}, 'ref': {'fsdp_config': {'param_offload': True, 'wrap_policy': {'min_num_params': 0}, 'fsdp_size': -1}, 'log_prob_micro_batch_size': 128, 'log_prob_use_dynamic_bsz': False, 'log_prob_max_token_len_per_gpu': 16384, 'ulysses_sequence_parallel_size': 1}, 'rollout': {'name': 'vllm', 'temperature': 1.0, 'top_k': -1, 'top_p': 0.95, 'prompt_length': 1024, 'response_length': 4096, 'dtype': 'bfloat16', 'gpu_memory_utilization': 0.7, 'ignore_eos': False, 'enforce_eager': True, 'free_cache_engine': True, 'load_format': 'dummy_dtensor', 'tensor_model_parallel_size': 1, 'max_num_batched_tokens': 8192, 'max_num_seqs': 1024, 'log_prob_micro_batch_size': 128, 'log_prob_use_dynamic_bsz': False, 'log_prob_max_token_len_per_gpu': 16384, 'do_sample': True, 'n': 1, 'n_agent': 2}}, 'critic': {'strategy': 'fsdp', 'optim': {'lr': 1e-05, 'lr_warmup_steps_ratio': 0.0, 'min_lr_ratio': None, 'warmup_style': 'constant', 'total_training_steps': 13250}, 'model': {'path': '~/models/deepseek-llm-7b-chat', 'tokenizer_path': '/fs-computility/mabasic/shared/models/Llama-3.2-3B-Instruct', 'override_config': {}, 'external_lib': None, 'enable_gradient_checkpointing': False, 'use_remove_padding': False, 'fsdp_config': {'param_offload': False, 'grad_offload': False, 'optimizer_offload': False, 'wrap_policy': {'min_num_params': 0}, 'fsdp_size': -1}}, 'ppo_mini_batch_size': 256, 'ppo_micro_batch_size': 64, 'forward_micro_batch_size': 64, 'use_dynamic_bsz': False, 'ppo_max_token_len_per_gpu': 32768, 'forward_max_token_len_per_gpu': 32768, 'ulysses_sequence_parallel_size': 1, 'ppo_epochs': 1, 'shuffle': False, 'grad_clip': 1.0, 'cliprange_value': 0.5}, 'reward_model': {'enable': False, 'strategy': 'fsdp', 'model': {'input_tokenizer': '/fs-computility/mabasic/shared/models/Llama-3.2-3B-Instruct', 'path': '~/models/FsfairX-LLaMA3-RM-v0.1', 'external_lib': None, 'use_remove_padding': False, 'fsdp_config': {'min_num_params': 0, 'param_offload': False}}, 'micro_batch_size': 64, 'max_length': None, 'ulysses_sequence_parallel_size': 1, 'use_dynamic_bsz': False, 'forward_max_token_len_per_gpu': 32768}, 'retriever': {'llm_ip': 'localhost', 'retriever_ip': 'localhost', 'topk': 5, 'search_mode': 'simulate', 'simulate_llm': 'None', 'start_threshold': 0.5, 'end_threshold': 0.5, 'temperature': 0.8, 'search_engine': 'wiki'}, 'algorithm': {'gamma': 1.0, 'lam': 1.0, 'adv_estimator': 'grpo', 'no_think_rl': False, 'kl_penalty': 'kl', 'kl_ctrl': {'type': 'fixed', 'kl_coef': 0.001}, 'state_masking': {'start_state_marker': '<information>', 'end_state_marker': '</information>'}}, 'trainer': {'total_epochs': 5, 'total_training_steps': None, 'project_name': 'Rethink Search Scaling', 'experiment_name': 'llama_3.1_8b_inst_grpo_init', 'logger': ['console', 'wandb'], 'nnodes': 1, 'n_gpus_per_node': 8, 'save_freq': 10000, 'test_freq': 16, 'critic_warmup': 0, 'default_hdfs_dir': '~/experiments/qa/ppo/llama_3.1_8b_inst_grpo_init', 'default_local_dir': 'checkpoints/Rethink Search Scaling/llama_3.1_8b_inst_grpo_init', 'do_search': True, 'max_turns': 2, 'val_before_train': False, 'val_only': False, 'reward_function': 'f1'}, '_wandb': {}}
2025-07-21 16:05:07,582 INFO    MainThread:827 [wandb_init.py:init():893] starting backend
2025-07-21 16:05:07,582 INFO    MainThread:827 [wandb_init.py:init():897] sending inform_init request
2025-07-21 16:05:07,584 INFO    MainThread:827 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-07-21 16:05:07,584 INFO    MainThread:827 [wandb_init.py:init():907] backend started and connected
2025-07-21 16:05:07,588 INFO    MainThread:827 [wandb_init.py:init():1005] updated telemetry
2025-07-21 16:05:07,638 INFO    MainThread:827 [wandb_init.py:init():1029] communicating run to backend with 90.0 second timeout
2025-07-21 16:05:08,632 INFO    MainThread:827 [wandb_init.py:init():1104] starting run threads in backend
2025-07-21 16:05:08,780 INFO    MainThread:827 [wandb_run.py:_console_start():2573] atexit reg
2025-07-21 16:05:08,780 INFO    MainThread:827 [wandb_run.py:_redirect():2421] redirect: wrap_raw
2025-07-21 16:05:08,780 INFO    MainThread:827 [wandb_run.py:_redirect():2490] Wrapping output streams.
2025-07-21 16:05:08,781 INFO    MainThread:827 [wandb_run.py:_redirect():2513] Redirects installed.
2025-07-21 16:05:08,782 INFO    MainThread:827 [wandb_init.py:init():1150] run started, returning control to user process
2025-07-21 16:11:51,787 INFO    MsgRouterThr:827 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-07-21 16:12:00,386 ERROR   ray_print_logs:827 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-21 16:12:00,387 ERROR   ray_print_logs:827 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-21 16:12:00,388 ERROR   ray_print_logs:827 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-21 16:12:00,388 ERROR   ray_print_logs:827 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-21 16:12:00,388 ERROR   ray_print_logs:827 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-21 16:12:00,388 ERROR   ray_print_logs:827 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-21 16:12:00,389 ERROR   ray_print_logs:827 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2494, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-21 16:12:00,389 ERROR   MainThread:827 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-21 16:12:00,389 ERROR   MainThread:827 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-21 16:12:00,390 ERROR   MainThread:827 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-21 16:12:00,390 ERROR   MainThread:827 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/root/miniconda3/envs/zerosearch/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
